# Generated by Django 3.2.8 on 2021-10-17 13:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaticMenuPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titel")),
                (
                    "template",
                    models.CharField(
                        choices=[("", "")],
                        default=None,
                        max_length=100,
                        verbose_name="Template",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "menu",
                    models.CharField(
                        choices=[("top", "Top Menü"), ("bottom", "Footer Menü")],
                        max_length=15,
                        verbose_name="Menü",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Menü Seiten",
                "verbose_name_plural": "Menü Seiten",
            },
        ),
    ]
