# Generated by Django 3.2.8 on 2021-10-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Menü",
                "verbose_name_plural": "Menüs",
            },
        ),
        migrations.AlterField(
            model_name="staticmenupage",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.menu",
                verbose_name="Menü",
            ),
        ),
    ]
