# Generated by Django 3.2.8 on 2021-10-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_staticmenupage_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticmenupage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.staticmenupage",
                verbose_name="Oberpunkt",
            ),
        ),
    ]
