# Generated by Django 3.2.8 on 2021-10-17 18:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_alter_staticmenupage_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticmenupage",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
