# Generated by Django 3.2.8 on 2021-10-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_alter_staticmenupage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticmenupage",
            name="root",
            field=models.BooleanField(default=False, verbose_name="Oberste Ebene"),
        ),
    ]
