# Generated by Django 3.2.8 on 2021-10-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_staticmenupage_root"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticmenupage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"root": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.staticmenupage",
                verbose_name="Oberpunkt",
            ),
        ),
    ]
