# Generated by Django 3.2.8 on 2021-11-27 22:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_alter_staticmenupage_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticmenupage",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
