# Generated by Django 3.2.8 on 2021-11-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_alter_staticmenupage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticmenupage",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Veröffentlicht"),
        ),
        migrations.AlterField(
            model_name="staticmenupage",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cms.menu",
                verbose_name="Menü",
            ),
        ),
        migrations.AlterField(
            model_name="staticmenupage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"root": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cms.staticmenupage",
                verbose_name="Oberpunkt",
            ),
        ),
        migrations.AlterField(
            model_name="staticmenupage",
            name="url",
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
