# Generated by Django 3.2.8 on 2021-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_auto_20211130_1705"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staticmenupage",
            name="url",
        ),
        migrations.AddField(
            model_name="staticmenupage",
            name="slug",
            field=models.SlugField(default="", max_length=200, verbose_name="Url"),
        ),
    ]
