# Generated by Django 3.2.8 on 2021-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_auto_20211130_1726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticmenupage",
            name="slug",
            field=models.SlugField(
                default="", max_length=200, unique=True, verbose_name="Url"
            ),
        ),
    ]
