# Generated by Django 3.2.9 on 2021-12-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_alter_staticmenupage_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staticmenupage",
            options={"verbose_name": "Seite", "verbose_name_plural": "Seiten"},
        ),
    ]
