# Generated by Django 3.2.8 on 2021-12-23 17:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_component_richtextfield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0012_alter_staticmenupage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titel")),
                (
                    "template",
                    models.CharField(
                        choices=[("", "")],
                        default=None,
                        max_length=100,
                        verbose_name="Template",
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Veröffentlicht"),
                ),
                (
                    "title_image",
                    models.ImageField(
                        blank=True, upload_to="blog/", verbose_name="Titelbild"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="", max_length=200, unique=True, verbose_name="Url"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "components",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.component",
                        verbose_name="Lösung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Eintrag",
                "verbose_name_plural": "Blog Einträge",
            },
        ),
    ]
