# Generated by Django 3.2.11 on 2022-01-11 16:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0022_component_richtextfield'),
        ('cms', '0012_alter_staticmenupage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmenupage',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='staticmenupage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='Url')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('published', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
                ('title_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Titelbild')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('components', models.ManyToManyField(blank=True, to='catalogue.Component', verbose_name='Lösungen')),
            ],
            options={
                'verbose_name': 'Blog Eintrag',
                'verbose_name_plural': 'Blog Einträge',
                'ordering': ['-created'],
            },
        ),
    ]
