# Generated by Django 3.2.8 on 2021-12-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_component_richtextfield"),
        ("cms", "0013_blogpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpage",
            options={
                "ordering": ["-created"],
                "verbose_name": "Blog Eintrag",
                "verbose_name_plural": "Blog Einträge",
            },
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="components",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="components",
            field=models.ManyToManyField(
                blank=True, to="catalogue.Component", verbose_name="Lösungen"
            ),
        ),
    ]
