# Generated by Django 3.2.8 on 2022-01-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20211223_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='template',
        ),
    ]
