# Generated by Django 3.2.11 on 2022-01-11 15:51

import cms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0015_remove_blogpage_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmenupage',
            name='author',
            field=models.ForeignKey(default=cms.models.get_default_author, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='staticmenupage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(default=cms.models.get_default_author, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
    ]
