# Generated by Django 3.2 on 2021-05-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20210430_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi',
            old_name='technical_specification',
            new_name='use',
        ),
    ]
