# Generated by Django 3.2.4 on 2021-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='allow_email',
            field=models.BooleanField(default=True, verbose_name='Erlaube Kontaktaufnahme per Mail'),
        ),
    ]
