# Generated by Django 3.2.4 on 2021-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_component_allow_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='search_url',
            field=models.TextField(default=None, verbose_name='Such-URL'),
        ),
    ]
