# Generated by Django 3.2.4 on 2021-08-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_component_allow_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.component')),
            ],
            options={
                'verbose_name': 'Gelöschte KI Komponente',
                'verbose_name_plural': 'Gelöschte KI Komponenten',
            },
            bases=('catalogue.component',),
        ),
    ]
