# Generated by Django 3.2.4 on 2021-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
