# Generated by Django 3.2.4 on 2021-08-28 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0008_component_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='last_modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to='auth.user', verbose_name='Zuletzt bearbeitet von'),
            preserve_default=False,
        ),
    ]
