# Generated by Django 3.2.4 on 2021-09-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_component_frontpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
    ]
