# Generated by Django 3.2.4 on 2021-09-25 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0010_component_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1000, verbose_name='Identifier')),
                ('query', models.CharField(blank=True, max_length=100, verbose_name='Anfrage')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('query_result_count', models.IntegerField(verbose_name='Anzahl Lösungen für die Anfrage', default=0)),
            ],
            options={
                'verbose_name': 'Suchverlauf',
                'verbose_name_plural': 'Suchverläufe',
            },
        ),
    ]
