# Generated by Django 3.2.4 on 2021-10-04 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_component_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='contact_address_city',
            field=models.CharField(blank=True, help_text='Stadt in der sich der Anbieter befindet', max_length=100, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_address_street',
            field=models.CharField(blank=True, help_text='Straße des Anbieters', max_length=100, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_address_zip',
            field=models.CharField(blank=True, help_text='PLZ in der sich der Anbieter befindet', max_length=100, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email Adresse des zuständigen Mitarbeiters', max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_person_name',
            field=models.CharField(default='Max Mustermann', help_text='Name des zuständigen Mitarbeiters', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Telefonnummer des zuständigen Mitarbeiters', max_length=17, validators=[django.core.validators.RegexValidator(message="Die Telefonnummer muss folgendes Format ausweisen: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefonnummer'),
        ),
    ]
