# Generated by Django 3.2.4 on 2021-10-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_searchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='identifier',
            field=models.CharField(max_length=100, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='query',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Anfrage'),
        ),
        migrations.CreateModel(
            name='ComponentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.component', verbose_name='Lösung')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.searchlog', verbose_name='Suchanfrage')),
            ],
            options={
                'verbose_name': 'Besuchte Lösungen',
                'verbose_name_plural': 'Besuchte Lösungen',
            },
        ),
    ]
