# Generated by Django 3.2.4 on 2021-10-05 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20211005_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='contact_address_city',
            field=models.CharField(blank=True, help_text='Stadt in der sich der Anbieter befindet', max_length=100, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_address_country',
            field=models.CharField(default='Deutschland', help_text='Land in dem sich der Anbieter befindet', max_length=100, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_address_street',
            field=models.CharField(blank=True, help_text='Straße des Anbieters', max_length=100, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_address_zip',
            field=models.CharField(blank=True, help_text='PLZ in der sich der Anbieter befindet', max_length=10, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email Adresse des zuständigen Mitarbeiters', max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact_person_name',
            field=models.CharField(default='Max Mustermann', help_text='Name des zuständigen Mitarbeiters', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Telefonnummer des zuständigen Mitarbeiters', max_length=17, validators=[django.core.validators.RegexValidator(message="Die Telefonnummer muss folgendes Format ausweisen: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefonnummer'),
        ),
        migrations.RenameField(
            model_name='component',
            old_name='manufacturer',
            new_name='contact_manufacturer'
        ),
        migrations.RenameField(
            model_name='component',
            old_name='additional_info',
            new_name='contact_additional_info'
        ),
        migrations.RemoveField(
            model_name='component',
            name='contact',
        ),
    ]
