# Generated by Django 3.2.4 on 2021-10-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_component_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='component',
            name='contact',
        ),
    ]
