# Generated by Django 3.2.7 on 2021-10-12 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_componentlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentlog',
            old_name='created',
            new_name='accessed'
        ),
    ]
