# Generated by Django 3.2.7 on 2021-10-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_feedback_sentiment'),
        ('catalogue', '0012_component_contact'),
        ('catalogue', '0013_auto_20211012_1909'),
    ]

    operations = [
    ]
