# Generated by Django 3.2.8 on 2021-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20211022_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='approved',
            field=models.BooleanField(default=False, help_text='Lösung wird nach Moderation freigegeben', verbose_name='Freigegeben'),
        ),
    ]
