# Generated by Django 3.2.8 on 2021-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_alter_component_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='product',
            new_name='long_description',
        ),
        migrations.AlterField(
            model_name='component',
            name='long_description',
            field=models.TextField(help_text='Ausführliche Beschreibung der Lösung', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='component',
            name='devices',
            field=models.CharField(help_text='Maschinen und IoT Devices, mit denen die Lösung kompatibel ist', max_length=1000, verbose_name='Maschinen / Steuerungen'),
        ),
        migrations.AlterField(
            model_name='component',
            name='it_environment',
            field=models.CharField(help_text='Anforderungen an die IT-Umgebung (inkl. IT Hardware) und an weitere Software/Bibliotheken, die für den Betrieb der Lösung notwendig sind', max_length=1000, verbose_name='IT Umgebung / Software'),
        ),
        migrations.AlterField(
            model_name='component',
            name='protocols',
            field=models.CharField(help_text='Schnittstellen und/oder Protokolle, die von der Lösung unterstützt werden', max_length=1000, verbose_name='Protokolle / Schnittstellen'),
        ),
    ]
