# Generated by Django 3.2.8 on 2021-11-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_rename_product_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(help_text='Kurze Beschreibung der Lösung', max_length=1000, verbose_name='Kurzbeschreibung'),
        ),
    ]
