# Generated by Django 3.2.8 on 2021-11-16 16:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_alter_component_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='long_description',
            field=ckeditor.fields.RichTextField(help_text='Ausführliche Beschreibung der Lösung', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='component',
            name='scenarios',
            field=ckeditor.fields.RichTextField(help_text='Beschreibung von Szenarien, in denen die Lösung bereits erfolgreich eingesetzt wurde', verbose_name='Szenarien / Use cases'),
        ),
    ]
