# Generated by Django 3.2.8 on 2021-12-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_component_richtextfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(verbose_name="Titelbild", help_text="Titelbild der Lösung", blank=True, upload_to='componentImages'),
        ),
    ]
