# Generated by Django 3.2.9 on 2022-01-10 16:18

import catalogue.models.component
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('catalogue', '0023_componentfile'), ('catalogue', '0024_alter_componentfile_id'), ('catalogue', '0025_alter_componentfile_file'), ('catalogue', '0026_auto_20220110_1632')]

    dependencies = [
        ('catalogue', '0022_component_richtextfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to=catalogue.models.component.get_file_path, verbose_name='Datei')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.component')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
            },
        ),
    ]
