# Generated by Django 3.2.8 on 2021-12-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_component_richtextfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='comp_files')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.component')),
            ],
            options={
                'verbose_name': 'Anhang',
                'verbose_name_plural': 'Anhang',
            },
        ),
    ]
