# Generated by Django 3.2.11 on 2022-01-10 18:20

import catalogue.models.component
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_componentfile_squashed_0026_auto_20220110_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, help_text='Mindestbreite 1153px', upload_to=catalogue.models.component.get_image_path, validators=[catalogue.models.component.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Titelbild'),
        ),
    ]
