# Generated by Django 3.2.8 on 2021-12-16 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_componentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
