# Generated by Django 3.2.8 on 2021-12-17 18:12

import catalogue.models.component
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_component_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, help_text='Titelbild der Lösung', upload_to=catalogue.models.component.get_file_path, validators=[catalogue.models.component.validate_image_size], verbose_name='Titelbild'),
        ),
    ]
