# Generated by Django 3.2.8 on 2021-12-17 16:28

import catalogue.models.component
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_alter_componentfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentfile',
            name='file',
            field=models.FileField(blank=True, upload_to=catalogue.models.component.get_file_path),
        ),
    ]
