# Generated by Django 3.2.9 on 2022-01-10 15:32

import catalogue.models.component
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_alter_componentfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentfile',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterField(
            model_name='componentfile',
            name='file',
            field=models.FileField(blank=True, upload_to=catalogue.models.component.get_file_path, verbose_name='Datei'),
        ),
    ]
